package mps.sample.plugin.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.pluginparts.actions.GeneratedActionGroup;
import jetbrains.mps.logging.Logger;
import jetbrains.mps.ide.actions.Tools_ActionGroup;

public class My_own_group_ActionGroup extends GeneratedActionGroup {
  private static Logger LOG = Logger.getLogger(My_own_group_ActionGroup.class);
  public static final String ID = "mps.sample.plugin.plugin.My own group";

  public My_own_group_ActionGroup() {
    super("MyGroup", ID);
    this.setIsAlwaysVisible(false);
    this.setIsInternal(false);
    this.setPopup(true);
    try {
      this.addAction("mps.sample.plugin.plugin.ImportCrowd_Action", "mps.sample.plugin");
    } catch (Throwable t) {
      LOG.error("User group error", t);
    }
  }

  public void adjust() {
    this.insertGroupIntoAnother(Tools_ActionGroup.ID, null);
  }

}
