package mps.sample.plugin.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.lang.core.structure.INamedConcept;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class Crowd extends BaseConcept implements INamedConcept {
  public static final String concept = "mps.sample.plugin.structure.Crowd";
  public static final String NAME = "name";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String MEMBER = "member";

  public Crowd(SNode node) {
    super(node);
  }

  public String getName() {
    return this.getProperty(Crowd.NAME);
  }

  public void setName(String value) {
    this.setProperty(Crowd.NAME, value);
  }

  public String getShortDescription() {
    return this.getProperty(Crowd.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(Crowd.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(Crowd.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(Crowd.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(Crowd.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(Crowd.VIRTUAL_PACKAGE, value);
  }

  public int getMembersCount() {
    return this.getChildCount(Crowd.MEMBER);
  }

  public Iterator<Person> members() {
    return this.children(Person.class, Crowd.MEMBER);
  }

  public List<Person> getMembers() {
    return this.getChildren(Person.class, Crowd.MEMBER);
  }

  public void addMember(Person node) {
    this.addChild(Crowd.MEMBER, node);
  }

  public void insertMember(Person prev, Person node) {
    this.insertChild(prev, Crowd.MEMBER, node);
  }


  public static Crowd newInstance(SModel sm, boolean init) {
    return (Crowd)SModelUtil_new.instantiateConceptDeclaration("mps.sample.plugin.structure.Crowd", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static Crowd newInstance(SModel sm) {
    return Crowd.newInstance(sm, false);
  }

}
