package mps.sample.plugin.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.lang.core.structure.INamedConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class Person extends BaseConcept implements INamedConcept {
  public static final String concept = "mps.sample.plugin.structure.Person";
  public static final String STREET = "street";
  public static final String NUMBER = "number";
  public static final String ZIP = "zip";
  public static final String CITY = "city";
  public static final String NAME = "name";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";

  public Person(SNode node) {
    super(node);
  }

  public String getStreet() {
    return this.getProperty(Person.STREET);
  }

  public void setStreet(String value) {
    this.setProperty(Person.STREET, value);
  }

  public String getNumber() {
    return this.getProperty(Person.NUMBER);
  }

  public void setNumber(String value) {
    this.setProperty(Person.NUMBER, value);
  }

  public String getZip() {
    return this.getProperty(Person.ZIP);
  }

  public void setZip(String value) {
    this.setProperty(Person.ZIP, value);
  }

  public String getCity() {
    return this.getProperty(Person.CITY);
  }

  public void setCity(String value) {
    this.setProperty(Person.CITY, value);
  }

  public String getName() {
    return this.getProperty(Person.NAME);
  }

  public void setName(String value) {
    this.setProperty(Person.NAME, value);
  }

  public String getShortDescription() {
    return this.getProperty(Person.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(Person.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(Person.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(Person.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(Person.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(Person.VIRTUAL_PACKAGE, value);
  }


  public static Person newInstance(SModel sm, boolean init) {
    return (Person)SModelUtil_new.instantiateConceptDeclaration("mps.sample.plugin.structure.Person", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static Person newInstance(SModel sm) {
    return Person.newInstance(sm, false);
  }

}
