package mps.sample.plugin.structure;

/*Generated by MPS */

import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.Language;
import jetbrains.mps.smodel.MPSModuleRepository;

public class Plugin_Language {
  public static ModuleReference MODULE_REFERENCE = ModuleReference.fromString("681e5239-d663-468b-97f7-cc7a4fa4cdea(mps.sample.plugin)");

  public static Language get() {
    return (Language)MPSModuleRepository.getInstance().getModule(MODULE_REFERENCE);
  }

}
